stages:
- name: 编译项目
  steps:
  - runScriptConfig:
      image: jiangqi.docker.com:30002/jiangqi/maven:v1
      shellScript: mvn clean install -Dmaven.test.skip=true
- name: 创建微服务2镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./serviceTwo/Dockerfile
      buildContext: .
      tag: jiangqi/service-two:v1
      pushRemote: true
      registry: 192.168.1.6:30003
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: https://xwx6wxd1.mirror.aliyuncs.com/
- name: 创建服务网关镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./callService/Dockerfile
      buildContext: .
      tag: jiangqi/call-service:v1
      pushRemote: true
      registry: 192.168.1.6:30003
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: https://xwx6wxd1.mirror.aliyuncs.com/
- name: 发布服务
  steps:
  - applyYamlConfig:
      path: ./example.yaml
timeout: 60
notification: {}
