apiVersion: v1
kind: Service
metadata:
  name: servicetwo
  namespace: default
  labels:
    app: servicetwo
spec:
  ports:
  - name: servicetwo
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: servicetwo
    tier: test

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: servicetwo
  namespace: default
spec:
  rules:
  - host: servicetwo.default.103.132.191.11.xip.io
    http:
      paths:
      - path:
        backend:
          serviceName: servicetwo
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: callservice
  namespace: default
  labels:
    app: callservice
spec:
  ports:
  - name: callservice
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: callservice
    tier: test

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: callservice
  namespace: default
spec:
  rules:
  - host: callservice.default.103.132.191.11.xip.io
    http:
      paths:
      - path:
        backend:
          serviceName: callservice
          servicePort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicetwo
  namespace: default
  labels:
    app: servicetwo
    tier: test
spec:
  selector:
    matchLabels:
      app: servicetwo
      tier: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: servicetwo
        tier: test
    spec:
      containers:
      - image: jiangqi.docker.com:30002/jiangqi/service-two:v1
        name: servicetwo
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - containerPort: 8080
          name: servicetwo
        volumeMounts:
        - name: config
          mountPath: /jqtest
      volumes:
      - configMap:
          defaultMode: 256
          name: servicetwo-config
          optional: false
        name: config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callservice
  namespace: default
  labels:
    app: callservice
    tier: test
spec:
  selector:
    matchLabels:
      app: callservice
      tier: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: callservice
        tier: test
    spec:
      containers:
      - image: jiangqi.docker.com:30002/jiangqi/call-service:v1
        name: callservice
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - containerPort: 8080
          name: callservice
        volumeMounts:
        - name: config
          mountPath: /jqtest
      volumes:
      - configMap:
          defaultMode: 256
          name: callservice-config
          optional: false
        name: config